
  name: mkchromecast-compiaffefork
  version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
  summary: This is a program to cast your Linux audio to your Google Cast devices or Sonos speakers. It can also cast video files.
  description:
    It is written in Python, and it can stream via node.js, parec (Linux), ffmpeg, or avconv. 
    Mkchromecast is capable of using lossy and lossless audio formats provided that ffmpeg, avconv (Linux), or parec (Linux) are installed.
    It also supports Multi-room group playback, and 24-bit/96kHz high audio resolution. 
    Additionally, a system tray menu is available.

  grade: devel # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots

  parts:
    my-part:
      # See 'snapcraft plugins'
      plugin: nil
  
